CREATE TABLE POST(
    ID      SERIAL PRIMARY KEY,
    CONTENT VARCHAR(255)           NOT NULL,
    CREATED TIMESTAMP           NOT NULL,
    UPDATED TIMESTAMP           NOT NULL
);

INSERT INTO POST (CONTENT,CREATED,UPDATED) VALUES ('Post1', '2014-04-04 20:00:00', '2014-04-04 20:00:00');
INSERT INTO POST (CONTENT,CREATED,UPDATED) VALUES ('Post2', '2015-04-04 20:00:00', '2015-04-04 20:00:00');
INSERT INTO POST (CONTENT,CREATED,UPDATED) VALUES ('Post3', '2016-04-04 20:00:00', '2016-04-04 20:00:00');


CREATE TABLE REGION(
    ID      SERIAL PRIMARY KEY,
    NAME    VARCHAR(255)     NOT NULL
);

INSERT INTO REGION (NAME) VALUES ('RIGA');
INSERT INTO REGION (NAME) VALUES ('KIEV');
INSERT INTO REGION (NAME) VALUES ('PRAHA');

CREATE TABLE USERSERVLET (
        ID           SERIAL PRIMARY KEY,
        FIRSTNAME    VARCHAR(255)     NOT NULL,
        LASTNAME     VARCHAR(255)     NOT NULL,
        ROLE         VARCHAR(255)     NOT NULL,
        REGION_ID    INT,
            CONSTRAINT fk_region
                FOREIGN KEY(region_id)
                    REFERENCES REGION(id)
                ON DELETE CASCADE
);

INSERT INTO USERSERVLET (FIRSTNAME, LASTNAME, ROLE, REGION_ID) VALUES ('Ievgen', 'Chap', 'USER', 1);
INSERT INTO USERSERVLET (FIRSTNAME, LASTNAME, ROLE, REGION_ID) VALUES ('Ievgen12', 'Chap123', 'ADMIN', 2);


CREATE TABLE USERPOST (
        ID_USER     INT     NOT NULL,
        ID_POST     INT     NOT NULL,

    CONSTRAINT fk_user_id
        FOREIGN KEY(ID_USER)
    REFERENCES USERSERVLET(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT fk_post_id
            FOREIGN KEY(ID_POST)
                REFERENCES POST(id)
                ON DELETE CASCADE
                ON UPDATE CASCADE
);

INSERT INTO USERPOST (ID_USER, ID_POST) VALUES (1, 1);
INSERT INTO USERPOST (ID_USER, ID_POST) VALUES (1, 2);
INSERT INTO USERPOST (ID_USER, ID_POST) VALUES (1, 3);
INSERT INTO USERPOST (ID_USER, ID_POST) VALUES (2, 1);
INSERT INTO USERPOST (ID_USER, ID_POST) VALUES (2, 2);
